# Generated by Django 5.2.5 on 2025-08-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
    ]
