# Generated by Django 5.2.5 on 2025-08-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tasks_delete_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='created_at',
        ),
    ]
